name: Keep Render Server Alive

on:
  schedule:
    # Run every 5 minutes (*/5 * * * *)
    # Note: GitHub Actions has a minimum interval of 5 minutes for scheduled workflows
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  ping-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Render Server
        run: |
          echo "Pinging server to keep it alive..."
            # Replace YOUR_RENDER_URL with your actual Render service URL
          # Example: https://your-app-name.onrender.com
          RENDER_URL="https://attendence-jmza.onrender.com/"
          if [ -z "$RENDER_URL" ]; then
            RENDER_URL="https://attendence-jmza.onrender.com/"
          fi
          
          # Ping the health check endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" "$RENDER_URL/api/health" || echo "000")
          
          if [ "$response" = "200" ]; then
            echo "✅ Server is alive! Response code: $response"
          else
            echo "⚠️ Server responded with code: $response"
            # Try pinging the root URL as fallback
            root_response=$(curl -s -o /dev/null -w "%{http_code}" "$RENDER_URL" || echo "000")
            echo "Root URL response code: $root_response"
          fi
          
          echo "Ping completed at $(date)"
      
      - name: Log Status
        run: |
          echo "Keep-alive job completed successfully"
